### ISSUE TITLE
Does web-push work?

### ISSUE THREAD

**Issue by VICTORVICKIE** [svelte-u/playground#1]
I was browsing GitHub for usage of web-push in svelte and stumbled on this project, does the web-push implementation of push notification works?

**Comment by Mohamed-Kaizen** [comment]
yea, i was test it today and was working fine . You need to generate vapid keys then you need to registered in web-push and serviceWorker, [you can see this code of how to registered in the service worker](https://github.com/svelte-u/browser/blob/main/src/push_notification/index.ts). OR you can clone this repo and test it locally b/c i generated a vapid keys for this demo
